spring:
  main:
    banner-mode: 'OFF'
    # Turn off web application, we only want to migrate
    web-application-type: NONE
  flyway:
    enabled: true
    default-schema: speedyteller
    schemas: speedyteller
jwt:
  secret: ~
  issuer: ~
logging:
  level:
    org.springframework.core.env: TRACE
